AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  serverless-api

  Sample SAM Template for serverless-api

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 6

Resources:
  SemiautomaticFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties: 
      PackageType: Image # Properties for Dockerized API
      Architectures:
        - x86_64
      # CodeUri: auth-api/
      # Handler: main.handler
      # Runtime: python3.8
      Events:
        Proxy:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /{proxy+}
            Method: any
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: ./auth-api
      DockerTag: test

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  SemiautomaticApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  SemiautomaticFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt SemiautomaticFunction.Arn
  SemiautomaticFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt SemiautomaticFunctionRole.Arn
