AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  serverless-api

  Sample SAM Template for serverless-api

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 90
    Environment:
        Variables:
          LOG_LEVEL: DEBUG
          PYTHONPATH: app
          THREADS: 4
          X_API_KEY: "1234"

Resources:
  CMSFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties: # Properties for Dockerized API
      PackageType: Image
      Architectures:
        - x86_64
      # CodeUri: cms-api/
      # Handler: main.handler
      # Runtime: python3.8
      Events:
        Health:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /health
            Method: get
        getUserId:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /users/{userid}
            Method: post
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: ./example-api
      DockerTag: test

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  CMSApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  CMSFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt CMSFunction.Arn
  CMSFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt CMSFunctionRole.Arn
